### ISSUE TITLE
ampersand in value is not encoded

### ISSUE THREAD

**Issue by MightyPork** [algesten/qstring#1]
Hello! I'm testing your library and found this issue:

```rust
use qstring::QString;
use std::string::ToString;

let qs = QString::new(vec![("foo","b&r")]);
assert_eq!("foo=b%26r", qs.to_string());
```

```none
thread 'url::test_a' panicked at 'assertion failed: `(left == right)`
  left: `"foo=b%26r"`,
 right: `"foo=b&r"`', utils/src/url.rs:169:5
```

I see you use `percent_encoding::QUERY_ENCODE_SET`, which does not include ampersand. I think that's incorrect here, you should encode ampersand (and probably `?` and `=`) as well.

The same issue occurs inside keys, but there it's less likely to happen.

**Comment by algesten** [comment]
Sorted in qstring 0.7.2. Thanks.
